### ISSUE TITLE
Error: Unexpected EOF

### ISSUE THREAD

**Issue by Uil-Yhtomit** [Donders-Institute/dr-tools#16] opened 2023-05-12 04:53 UTC
When I used this repocli tool on a ubuntu server to download the meg narrative dataset, it failed to download some files. 
![1683866932914](https://github.com/Donders-Institute/dr-tools/assets/131793704/c4af4c14-c3a9-4af6-94a1-93c382b001a4)

But if I download directly from the [website](https://data.donders.ru.nl/collections/di/dccn/DSC_3011085.05_995?9), the downloaded files are fine.

I used the repocli.x86_64 from the 0.8.0 release.

**Comment by hurngchunlee** [comment] 2023-05-12 09:58
@Uil-Yhtomit I can reproduce the same issue via a simple curl command to download the large file.  I believe it is due to a limitation on the server.  I have contacted the DR developers to take a look of this issue.  There is nothing I can do from the repocli side.

In the future, please report such type of issue via the DR support: datasupport@donders.ru.nl.

**Comment by hurngchunlee** [comment] 2023-05-12 11:11
@Uil-Yhtomit it is confirmed by the DR developer that it is due to a limitation of 1GB temporary file cache on the web proxy server.  They will adjust it accordingly to fix it.  Current workaround is to download them from the DR website as you already found out yourself.

As the issue is unrelated to the repocli, I am closing it now.

**Closed by hurngchunlee** 2023-05-12 11:11 UTC

**Comment by Uil-Yhtomit** [comment] 2023-05-13 04:24
Thanks. 

Actually, there seems to be a problem with directly downloading from the website. After downloading about 5~6G, it will automatically terminate. 😔

**Comment by hurngchunlee** [comment] 2023-05-15 15:37
@Uil-Yhtomit According to the DR developers, the 1GB limitation should be removed. You may try the download again with the repocli.
